name: Playwright Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install playwright browsers
        run: npx playwright install
        
      - name: Run create account.spec.js file
        env:
          # SALESFORCE_USERNAME: ${{ secrets.SALESFORCE_USERNAME }}
          # SALESFORCE_PASSWORD: ${{ secrets.SALESFORCE_PASSWORD }}
        run: npm run login-sf --debug


      # - name: Run Postman Script to Remove Accounts
      #   env:
      #     SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
      #     SF_CLIENT_SECRET: ${{ secrets.SF_CLIENT_SECRET }}
      #   run: node ./tests/postman/removeaccounts.js
