name: Playwright Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install playwright browsers
        run: npx playwright install

      - name: Install missing dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwoff1 libvpx7 libevent-2.1-7 libopus0 \
          libgstallocators-1.0-0 libgstapp-1.0-0 libgstpbutils-1.0-0 libgstaudio-1.0-0 \
          libgsttag-1.0-0 libgstvideo-1.0-0 libgstgl-1.0-0 libgstcodecparsers-1.0-0 \
          libgstfft-1.0-0 libharfbuzz-icu0 libhyphen0 libmanette-0.2-0 \
          libflite1 libflite-usenglish1 libflite-cmu-grapheme-lang1 libflite-cmu-grapheme-lex1 \
          libflite-cmu-indic-lang1 libflite-cmu-indic-lex1 libflite-cmulex1 \
          libflite-cmu-time-awb1 libflite-cmu-us-awb1 libflite-cmu-us-kal16 libflite-cmu-us-kal1 \
          libflite-cmu-us-rms1 libflite-cmu-us-slt1 libgles2 libx264-155
      
        
      - name: Run create account.spec.js file
        env:
          SALESFORCE_USERNAME: ${{ secrets.SALESFORCE_USERNAME }}
          SALESFORCE_PASSWORD: ${{ secrets.SALESFORCE_PASSWORD }}
        run: npm run login-sf --headless --workers=6 --debug


      # - name: Run Postman Script to Remove Accounts
      #   env:
      #     SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
      #     SF_CLIENT_SECRET: ${{ secrets.SF_CLIENT_SECRET }}
      #   run: node ./tests/postman/removeaccounts.js
